---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: argocd
  namespace: argocd
spec:
  gatewayClassName: cilium
  listeners:
    - hostname: argo.reprogle.org
      name: argocd-listener
      port: 80
      protocol: HTTP