# Default configuration for Cobalt. This configures an IngressRoute on the websecure port (443) and forwards it to port 80 of the cobalt service. Same applies for the API
# We use internal DNS for this (AdGuard Home DNS Rewrites), cobalt.reprogle.org and api.cobalt.reprogle.org are not publicly available DNS records.
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cobalt-ingress-secure
  namespace: cobalt
  labels:
    app: cobalt
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`cobalt.reprogle.org`)
    priority: 10
    services:
    - name: cobalt-server
      port: 80
  - kind: Rule
    match: Host(`api.cobalt.reprogle.org`)
    priority: 10
    services:
    - name: cobalt-api
      port: 80
  tls:
    certResolver: default

---
# This IngressRoute exists to force http to be https. We don't place the API here because its value is hardcoded in the environment variables, so we don't need to worry
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cobalt-ingress-web
  namespace: cobalt
  labels:
    app: cobalt
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`cobalt.reprogle.org`)
    priority: 11
    services:
    - name: cobalt-server
      port: 80
    middlewares:
    - name: redirect-https

---
# This middleware redirects http to https
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: cobalt
spec:
  redirectScheme:
    scheme: https
    permanent: true