apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-cert
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - "longhorn.reprogle.org"