apiVersion: v1
kind: Endpoints
metadata:
  name: adguardhome-sync
subsets:
  - addresses:
      - ip: 10.2.1.111
      - ip: 10.2.1.101
    ports:
      - port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: adguardhome-sync
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: adguardhome-sync
