apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobalt
  namespace: cobalt
spec:
  selector:
    matchLabels:
      app: cobalt
  template:
    metadata:
      labels:
        app: cobalt
    spec:
      containers:
      - name: cobalt
        image: ghcr.io/wukko/cobalt:10
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9001
        env:
        - name: API_URL
          value: "https://api.cobalt.reprogle.org"
        - name: WEB_URL
          value: "https://cobalt.reprogle.org"
