api: v1
kind: Service
metadata:
  name: cobalt-server
  namespace: cobalt
spec:
  selector:
    app: cobalt
  ports:
  - protocol: TCP
    port: 443
    targetPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: cobalt
spec:
  selector:
    app: cobalt-api
  ports:
  - port: 443
    targetPort: 9000