apiVersion: v1
kind: Service
metadata:
  name: cobalt-server
  namespace: cobalt
spec:
  selector:
    app: cobalt
  ports:
  - port: 80
    targetPort: 9001
    name: http

---

apiVersion: v1
kind: Service
metadata:
  name: cobalt-api
  namespace: cobalt
spec:
  selector:
    app: cobalt-api
  ports:
  - port: 80
    targetPort: 9000
    name: http